Solução para apple-app-site dev e prod
caronae/caronae-site pull request #6
Opened 2018-10-25 18:56 UTC by JorgeMadson

Solução simples pra resolver o problema das variáveis de ambiente dev e prod no apple-app-site-association

2018-10-25 20:36 UTC, macecchi requested changes
Muito obrigado, @JorgeMadson! A ideia era essa mesmo!
Posso te pedir só pra fazer umas mudanças?

* O script do `cat` tem que estar na mesma linha de cima, no final do que existe seguido de um `&&`, porque esse comando é executado via ssh. Desse jeito executaria o comando apenas no ambiente do CI e não no servidor remoto :)
* Não precisa do `../`, já que no comando anterior já foi feito um `cd` pro diretório certo :)
* Substitui o `>>` por `>`. O `>>` faz uma concatenação no arquivo, caso já exista, enquanto o `>` sobrescreve. Se usarmos o `>>` só vai funcionar da primeira vez 
* Pode deletar o arquivo antigo do `apple-app-site-association`

2018-10-25 20:39 UTC, macecchi commented
Ficaria assim:

```suggestion
              ssh -o StrictHostKeyChecking=No -A $CARONAE_DEV_USER@$CARONAE_DEV_HOST -p $CARONAE_DEV_PORT "cd /var/caronae/caronae-site && sudo git fetch origin develop && sudo git reset --hard origin/develop && sudo cat ./apple-app-site-association-dev > ./apple-app-site-association"
```

2018-10-25 21:15 UTC, JorgeMadson commented
Ok, verdade! Muito bom o feedback, vou corrigir ele agora.

2018-10-25 21:30 UTC, JorgeMadson commented
Corrigi :+1: 
Se escapou alguma coisa só falar!

2018-10-25 23:52 UTC, merged

2018-10-26 00:19 UTC, macecchi commented
Mergeei!

Acabei descobrindo que o `cat` não funcionou muito bem por causa do sudo (a parte depois do > não pega o sudo) aí acabei achando mais fácil trocar por um link simbólico, que ficou assim:

```bash
sudo ln -sf apple-app-site-association-prod apple-app-site-association
```

Também acabei lembrando que preciso atualizar o config.yml pro formato do CircleCI 2.0. Como esse repo não é atualizado com tanta frequência acabei esquecendo. :P 

De qualquer maneira, muuito obrigado pela contribuição!

2018-10-26 00:19 UTC, macecchi commented
closing #3